import type { Snapshot, SleepRecord } from './types';

// Civil-date arithmetic uses UTC noon, never elapsed local days (23/25-hour DST days).
export function isCivilDate(value: unknown): value is string { return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(value + 'T12:00:00Z')) && new Date(value + 'T12:00:00Z').toISOString().slice(0, 10) === value; }
export function localDate(value = new Date()): string { return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`; }
export function addDays(date: string, days: number): string { if (!isCivilDate(date)) throw new Error('Fecha inválida.'); const d = new Date(date + 'T12:00:00Z'); d.setUTCDate(d.getUTCDate() + days); return d.toISOString().slice(0, 10); }
export function weekStart(date: string): string { if (!isCivilDate(date)) throw new Error('Fecha inválida.'); const day = new Date(date + 'T12:00:00Z').getUTCDay(); return addDays(date, -((day + 6) % 7)); }
export function sleepMinutes(sleep: SleepRecord): number { return (Date.parse(sleep.wakeTime) - Date.parse(sleep.sleepStart || sleep.bedtime)) / 60000; }
export function mean(values: number[]): number | null { return values.length ? values.reduce((a, b) => a + b, 0) / values.length : null; }
export function standardDeviation(values: number[]): number | null { const avg = mean(values); return avg === null || values.length < 2 ? null : Math.sqrt(values.reduce((total, v) => total + (v - avg) ** 2, 0) / values.length); }
export interface WeeklyMetrics { start: string; end: string; days: number; sleepAverageMinutes: number | null; sleepDays: number; sleepVariabilityMinutes: number | null; studyMinutes: number; studySessions: number; studyOutputs: number; activityMinutes: number; activitySessions: number; activityDays: number; routineCompleted: number; routinePlanned: number; routineCompletion: number | null; leisureMinutes: number; intentionalLeisureMinutes: number; intentionalLeisurePercent: number | null; energyAverage: number | null; energyDays: number; moodAverage: number | null; concentrationAverage: number | null; stressAverage: number | null; }
export function weeklyMetrics(data: Snapshot, date: string, through?: string): WeeklyMetrics {
 const start = weekStart(date), fullEnd = addDays(start, 6), end = through && through < fullEnd ? (through < start ? start : through) : fullEnd;
 const range = <T extends { date: string }>(rows: T[]) => rows.filter(r => r.date >= start && r.date <= end);
 const sleep = range(data.sleep), study = range(data.studySessions), activity = range(data.activities), routine = range(data.routineHistory), leisure = range(data.leisureSessions), checkins = range(data.checkIns);
 // First average within each recorded day, then across days to avoid weighting frequent check-ins.
 const signal = (key: 'energy' | 'mood' | 'stress' | 'concentration') => mean([...new Set(checkins.map(c => c.date))].map(day => mean(checkins.filter(c => c.date === day).map(c => c[key]))!));
 const duration = (rows: { durationMinutes: number }[]) => rows.reduce((sum, r) => sum + r.durationMinutes, 0);
 const totalLeisure = duration(leisure), intentional = duration(leisure.filter(r => r.intentional));
 return { start, end, days: Math.round((Date.parse(end) - Date.parse(start)) / 86400000) + 1, sleepAverageMinutes: mean(sleep.map(sleepMinutes)), sleepDays: sleep.length, sleepVariabilityMinutes: standardDeviation(sleep.map(sleepMinutes)), studyMinutes: duration(study), studySessions: study.length, studyOutputs: study.filter(s => s.output.trim()).length, activityMinutes: duration(activity), activitySessions: activity.length, activityDays: new Set(activity.map(s => s.date)).size, routineCompleted: routine.filter(r => r.completedAt).length, routinePlanned: routine.length, routineCompletion: routine.length ? routine.filter(r => r.completedAt).length / routine.length * 100 : null, leisureMinutes: totalLeisure, intentionalLeisureMinutes: intentional, intentionalLeisurePercent: totalLeisure ? intentional / totalLeisure * 100 : null, energyAverage: signal('energy'), energyDays: new Set(checkins.map(c => c.date)).size, moodAverage: signal('mood'), stressAverage: signal('stress'), concentrationAverage: signal('concentration') };
}
export function compareWeeks(data: Snapshot, date: string) { const start = weekStart(date), current = weeklyMetrics(data, date, date), previousStart = addDays(start, -7), previousEnd = addDays(date, -7); return { current, previous: weeklyMetrics(data, previousStart, previousEnd), partial: date !== addDays(start, 6) }; }
export function dailyTrend(data: Snapshot, endDate: string) { return Array.from({ length: 7 }, (_, i) => { const date = addDays(endDate, i - 6), sleep = data.sleep.find(s => s.date === date), checks = data.checkIns.filter(c => c.date === date); return { date, sleepMinutes: sleep ? sleepMinutes(sleep) : null, energy: mean(checks.map(c => c.energy)), mood: mean(checks.map(c => c.mood)), studyMinutes: data.studySessions.filter(s => s.date === date).reduce((n, s) => n + s.durationMinutes, 0) }; }); }
