import { useEffect, useRef, type ReactNode } from 'react';
import { ArrowUpRight, X, Plus } from 'lucide-react';
export function Card({title,action,onAction,children,className=''}:{title:string;action?:string;onAction?:()=>void;children:ReactNode;className?:string}){return <section className={`card ${className}`}><div className="card-head"><h2>{title}</h2>{action&&<button className="text-button" onClick={onAction}>{action}<ArrowUpRight size={15}/></button>}</div>{children}</section>}
export function Empty({title,description,action,onAction}:{title:string;description:string;action?:string;onAction?:()=>void}){return <div className="empty"><span className="empty-star">✧</span><strong>{title}</strong><p>{description}</p>{action&&<button className="secondary" onClick={onAction}><Plus size={15}/>{action}</button>}</div>}
export function Ring({value,label,size=88}:{value:number|null;label?:string;size?:number}) {const v=value??0;return <div className="ring" style={{width:size,height:size}}><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="42" className="ring-track"/><circle cx="50" cy="50" r="42" className="ring-value" strokeDasharray={`${v*2.639} 264`}/></svg><span><strong>{value===null?'—':`${Math.round(v)}%`}</strong>{label&&<small>{label}</small>}</span></div>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) {const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.showModal();return()=>previous?.focus();},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-head"><div><span className="eyebrow">UN MOMENTO PARA TI</span><h2>{title}</h2></div><button aria-label="Cerrar" className="icon-button" onClick={onClose}><X size={20}/></button></div>{children}</dialog>}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function formatMinutes(value:number|null){if(value===null)return '—';const n=Math.round(value);return n>=60?`${Math.floor(n/60)} h ${n%60?`${n%60} min`:''}`:`${n} min`;}
export function shortDate(date:string){return new Date(date+'T12:00:00').toLocaleDateString('es-MX',{day:'numeric',month:'short'});}
export function timeOf(iso:string|null|undefined){return iso?new Date(iso).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit',hour12:false}):'—';}
