import type { ReactNode } from 'react';
import type { Snapshot, ActionPayloads, SleepRecord, CheckIn } from '../domain/types';
import type { WeeklyMetrics } from '../domain/analytics';
import type { EntryKind } from './EntryForm';
import { Card, Empty, Ring, formatMinutes, shortDate, timeOf } from './primitives';
import { Sun, Moon, Zap, Focus, Plus, BookOpen, Leaf, Smile, Heart, GraduationCap, Pencil, Coffee, Gamepad2, Music } from 'lucide-react';
type OpenEntry=(kind:EntryKind,initial?:object)=>void;
type EditButtons=(kind:EntryKind,row:{id:string},entity?:ActionPayloads['record.delete']['entity'])=>ReactNode;

interface Props{data:Snapshot;open:OpenEntry;quick:<K extends keyof ActionPayloads>(action:K,payload:ActionPayloads[K])=>Promise<void>;editButtons:EditButtons;}
export function StudyView({data,open,quick,editButtons}:Props){return <><div className="action-strip"><button className="secondary" onClick={()=>open('program')}><Plus size={17}/>Crear programa</button><button className="secondary" disabled={!data.programs.length} onClick={()=>open('subject')}>Añadir materia</button><button className="secondary" disabled={!data.subjects.length} onClick={()=>open('module')}>Añadir módulo</button></div>{data.programs.length?<div className="two-columns">{data.programs.map(p=>{const subjects=data.subjects.filter(s=>s.programId===p.id),modules=data.modules.filter(m=>subjects.some(s=>s.id===m.subjectId));return <Card key={p.id} title={p.title} action="Editar" onAction={()=>open('program',p)}><p className="muted">{p.description||'Un camino de aprendizaje propio.'}</p><div className="number-line"><span>Módulos completados</span><strong>{modules.filter(m=>m.completed).length}/{modules.length}</strong></div><div className="progress"><span style={{width:`${modules.length?100*modules.filter(m=>m.completed).length/modules.length:0}%`}}/></div><p className="hint">Completar contenido no equivale a dominarlo.</p>{subjects.map(s=><div className="subject" key={s.id}><h3>{s.title}<button className="icon-button" aria-label={`Editar materia ${s.title}`} onClick={()=>open('subject',s)}><Pencil size={13}/></button></h3>{data.modules.filter(m=>m.subjectId===s.id).map(m=><div className="module-row" key={m.id}><label><input type="checkbox" checked={m.completed} onChange={e=>void quick('module.save',{...m,completed:e.target.checked})}/>{m.title}</label><button className="icon-button" aria-label={`Editar módulo ${m.title}`} onClick={()=>open('module',{...m,programId:p.id})}><Pencil size={13}/></button></div>)}<button className="text-button" onClick={()=>open('module',{programId:p.id,subjectId:s.id})}><Plus size={14}/>Añadir módulo</button></div>)}<button className="secondary full" onClick={()=>open('study',{programId:p.id})}><Plus size={15}/>Registrar sesión</button></Card>})}</div>:<Card title="Construye tu plan"><Empty title="¿Qué te gustaría comprender?" description="Organiza un programa en materias y módulos. Registra tiempo y resultados por separado." action="Crear programa" onAction={()=>open('program')}/></Card>}<Card title="Sesiones de estudio">{data.studySessions.length?<div className="record-list">{[...data.studySessions].reverse().map(s=><div className="record-row" key={s.id}><GraduationCap size={22}/><div><strong>{data.programs.find(p=>p.id===s.programId)?.title}</strong><small>{shortDate(s.date)} · {s.output||'Sin resultado anotado'}{s.note&&` · ${s.note}`}</small></div><b>{formatMinutes(s.durationMinutes)}</b>{editButtons('study',s,'study')}</div>)}</div>:<Empty title="De la intención a la práctica" description="Tu primera sesión aparecerá aquí."/>}</Card></>;}
