import type { ReactNode } from 'react';
import type { Snapshot, ActionPayloads, SleepRecord, CheckIn } from '../domain/types';
import type { WeeklyMetrics } from '../domain/analytics';
import type { EntryKind } from './EntryForm';
import { Card, Empty, Ring, formatMinutes, shortDate, timeOf } from './primitives';
import { Sun, Moon, Zap, Focus, Plus, BookOpen, Leaf, Smile, Heart, GraduationCap, Pencil, Coffee, Gamepad2, Music } from 'lucide-react';
type OpenEntry=(kind:EntryKind,initial?:object)=>void;
type EditButtons=(kind:EntryKind,row:{id:string},entity?:ActionPayloads['record.delete']['entity'])=>ReactNode;

interface Props{data:Snapshot;date:string;week:WeeklyMetrics;partial:boolean;open:OpenEntry;
 go:(page:'wellness'|'study'|'leisure'|'review')=>void;sleep:SleepRecord|undefined;todayCheck:CheckIn|undefined;completion:number|null;done:number;
 routineList:ReactNode;dayEvents:{id:string;time:string;title:string;detail:string;done:boolean}[];studyTotal:number;leisureTotal:number;checks:ReactNode;sleepChart:ReactNode;}
export function TodayView({data,date,week,partial,open,go,sleep,todayCheck,completion,done,routineList,dayEvents,studyTotal,leisureTotal,checks,sleepChart}:Props){return <><div className="summary-grid"><div className="stat-card"><Sun className="orange"/><div><span>Despertar</span><small>Objetivo {data.preferences.wakeTarget}</small></div><strong>{timeOf(sleep?.wakeTime)}</strong><button onClick={()=>open('sleep',sleep)} className="mini-link">{sleep?'Editar':'Registrar'}</button></div><div className="stat-card"><Moon className="purple"/><div><span>Descanso</span><small>Objetivo personal {data.preferences.sleepTargetHours} h</small></div><strong>{formatMinutes(sleep?sleepMinutes(sleep):null)}</strong><span className="stat-foot">{sleep?(sleep.sleepStart?'Sueño estimado':'Tiempo en cama'):'Aún sin registro'}</span></div><div className="stat-card"><Zap className="orange"/><div><span>Energía</span><small>Último check-in de hoy</small></div><strong>{todayCheck?todayCheck.energy:'—'}<small>/5</small></strong><div className="progress"><span style={{width:`${todayCheck?todayCheck.energy*20:0}%`}}/></div></div><div className="stat-card"><Focus className="teal"/><div><span>Tu rutina</span><small>Actividades realizadas</small></div><strong>{completion===null?'—':`${Math.round(completion)}%`}</strong><div className="progress"><span style={{width:`${completion??0}%`}}/></div></div><div className="quote-card"><blockquote>Pequeñas decisiones<br/>también cambian<br/>grandes destinos.</blockquote><span>N O R Y U M</span></div></div>
 <div className="today-grid"><Card title="Mi rutina de hoy" action="Añadir" onAction={()=>open('routine')} className="routine-card"><div className="routine-progress"><Ring value={completion} label={`${done} de ${data.routines.length}`}/><div><strong>{data.routines.length?'A tu propio ritmo':'Tu punto de partida'}</strong><p>{data.routines.length?`${data.routines.length-done} actividades por realizar`:'No necesitas hacerlo todo.'}</p><button className="text-button" onClick={()=>open('template')}>Crear rutina recurrente <Plus size={13}/></button></div></div>{routineList}</Card>
 <Card title="Mi día de hoy" action="Calendario" onAction={()=>document.querySelector<HTMLInputElement>('[aria-label="Día seleccionado"]')?.showPicker()} className="timeline-card">{dayEvents.length?<div className="timeline">{dayEvents.map(e=><div className={`timeline-event ${e.done?'finished':''}`} key={e.id}><time>{e.time}</time><span className="timeline-dot"/><div><strong>{e.title}</strong><small>{e.detail}</small></div></div>)}</div>:<Empty title="Un día por escribir" description="Tus actividades previstas y tus check-ins aparecerán aquí."/>}<div className="timeline-total"><span>También registrado hoy</span><p><BookOpen size={15}/>{formatMinutes(studyTotal)} de estudio</p><p><Leaf size={15}/>{formatMinutes(leisureTotal)} de tiempo libre</p></div></Card>
 <div className="today-right"><Card title="Check-in de hoy" action={todayCheck?'Nuevo check-in':'Registrar'} onAction={()=>open('checkin')}>{checks}<p className="card-caption">{todayCheck?`Autorreporte · ${timeOf(todayCheck.recordedAt)} · escala de 1 a 5`:'Conocerte empieza por un momento de atención.'}</p></Card><Card title="Bienestar" action="Ver detalles" onAction={()=>go('wellness')}><div className="wellness-preview"><div><h3>Sueño · últimos 7 días</h3>{sleepChart}</div><dl><div><dt>Promedio esta semana</dt><dd>{formatMinutes(week.sleepAverageMinutes)}</dd></div><div><dt>Noches registradas</dt><dd>{week.sleepDays}/{week.days}</dd></div><div><dt>Movimiento</dt><dd>{week.activityDays} días</dd></div></dl></div></Card></div></div>
 <div className="bottom-grid"><Card title="Estudio" action="Ver mi plan" onAction={()=>go('study')}>{data.programs.length?<><div className="program-preview"><div className="program-icon"><GraduationCap size={31}/></div><div><h3>{data.programs[0].title}</h3><p>{data.programs[0].description||'Tu programa personal de aprendizaje'}</p></div></div><div className="number-line"><span>Esta semana</span><strong>{formatMinutes(week.studyMinutes)}</strong></div><p className="hint">{week.studySessions} sesiones · {week.studyOutputs} resultados registrados</p><button className="secondary full" onClick={()=>open('study')}><Plus size={15}/>Registrar sesión</button></>:<Empty title="Aprende con dirección" description="Crea un programa y da el primer paso." action="Crear programa" onAction={()=>open('program')}/>}</Card>
 <Card title="Tiempo libre" action="Ver registros" onAction={()=>go('leisure')}><p className="muted">Tiempo libre intencional, una mente más plena.</p><div className="leisure-tiles">{[{title:'Lectura',icon:BookOpen},{title:'Videojuegos',icon:Gamepad2},{title:'Música',icon:Music},{title:'Descanso',icon:Coffee}].map(({title,icon:Icon})=><button key={title} onClick={()=>open('leisure',{category:title})}><Icon size={24}/><strong>{title}</strong><small>{formatMinutes(data.leisureSessions.filter(l=>l.category===title&&l.date>=week.start&&l.date<=date).reduce((n,l)=>n+l.durationMinutes,0))} esta semana</small></button>)}</div></Card>
 <Card title="Review semanal" action="Reflexionar" onAction={()=>go('review')}><p className="muted">{shortDate(week.start)} – {shortDate(week.end)} · {partial?'en curso':'semana completa'}</p><div className="review-preview"><Ring value={week.routineCompletion} label="rutina"/><div><div className="number-line"><span>Estudio</span><strong>{formatMinutes(week.studyMinutes)}</strong></div><div className="number-line"><span>Descanso</span><strong>{formatMinutes(week.sleepAverageMinutes)}</strong></div><div className="number-line"><span>Ocio intencional</span><strong>{formatMinutes(week.intentionalLeisureMinutes)}</strong></div></div></div><p className="serif-note">¿Qué quieres llevar contigo a la próxima semana?</p></Card></div></>;}
import { sleepMinutes } from '../domain/analytics';
