import type { ReactNode } from 'react';
import type { Snapshot, ActionPayloads, SleepRecord, CheckIn } from '../domain/types';
import type { WeeklyMetrics } from '../domain/analytics';
import type { EntryKind } from './EntryForm';
import { Card, Empty, Ring, formatMinutes, shortDate, timeOf } from './primitives';
import { Sun, Moon, Zap, Focus, Plus, BookOpen, Leaf, Smile, Heart, GraduationCap, Pencil, Coffee, Gamepad2, Music } from 'lucide-react';
type OpenEntry=(kind:EntryKind,initial?:object)=>void;
type EditButtons=(kind:EntryKind,row:{id:string},entity?:ActionPayloads['record.delete']['entity'])=>ReactNode;

interface Props{data:Snapshot;open:OpenEntry;checks:ReactNode;sleepChart:ReactNode;editButtons:EditButtons;}
export function WellnessView({data,open,checks,sleepChart,editButtons}:Props){return <><div className="action-strip"><button className="secondary" onClick={()=>open('sleep')}><Moon size={18}/>Registrar sueño</button><button className="secondary" onClick={()=>open('activity')}><Heart size={18}/>Registrar actividad</button><button className="secondary" onClick={()=>open('checkin')}><Smile size={18}/>Check-in rápido</button></div><div className="two-columns"><Card title="Descanso de los últimos 7 días">{sleepChart}<p className="hint">Los espacios vacíos representan noches sin registro. Duración estimada; no mide fases de sueño.</p></Card><Card title="Tu estado de hoy" action="Registrar" onAction={()=>open('checkin')}>{checks}<p className="hint">Cuatro señales independientes. No se combinan en una puntuación de bienestar.</p></Card></div><Card title="Registro de sueño" action="Añadir" onAction={()=>open('sleep')}>{data.sleep.length?<div className="record-list">{[...data.sleep].reverse().map(s=><div className="record-row" key={s.id}><Moon size={20}/><div><strong>{shortDate(s.date)} · {timeOf(s.bedtime)} → {timeOf(s.wakeTime)}</strong><small>{s.sleepStart?'Sueño estimado':'Tiempo en cama'} · calidad {s.quality??'—'}/5 {s.note&&`· ${s.note}`}</small></div><b>{formatMinutes(sleepMinutes(s))}</b>{editButtons('sleep',s,'sleep')}</div>)}</div>:<Empty title="El descanso también es información" description="Registra cuándo te acostaste y despertaste para comenzar."/>}</Card><div className="two-columns"><Card title="Movimiento" action="Añadir" onAction={()=>open('activity')}>{data.activities.length?<div className="record-list">{[...data.activities].reverse().map(s=><div className="record-row" key={s.id}><Heart size={18}/><div><strong>{s.type}</strong><small>{shortDate(s.date)} · esfuerzo {s.intensity}/5</small></div><b>{formatMinutes(s.durationMinutes)}</b>{editButtons('activity',s,'activity')}</div>)}</div>:<Empty title="Muévete a tu manera" description="Una caminata también cuenta."/>}</Card><Card title="Check-ins recientes">{data.checkIns.length?<div className="record-list">{[...data.checkIns].reverse().slice(0,30).map(s=><div className="record-row" key={s.id}><Smile size={18}/><div><strong>{shortDate(s.date)} · {timeOf(s.recordedAt)}</strong><small>Energía {s.energy} · ánimo {s.mood} · estrés {s.stress} · foco {s.concentration}</small>{s.note&&<small>{s.note}</small>}</div>{editButtons('checkin',s,'checkin')}</div>)}</div>:<Empty title="Haz una pequeña pausa" description="Unos segundos para saber cómo estás."/>}</Card></div></>;}
import { sleepMinutes } from '../domain/analytics';
