Unicode true
!include "MUI2.nsh"
Name "Noryum"
OutFile "..\release\Noryum-0.1.2-Setup-x64.exe"
InstallDir "$LOCALAPPDATA\Programs\Noryum"
RequestExecutionLevel user
SetCompressor /SOLID lzma
BrandingText "Noryum · See the patterns. Shape the outcome."
!define MUI_ICON "..\public\icon.ico"
!define MUI_UNICON "..\public\icon.ico"
!define MUI_ABORTWARNING
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_RUN "$INSTDIR\Noryum.exe"
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "Spanish"
VIProductVersion "0.1.2.0"
VIAddVersionKey /LANG=1034 "ProductName" "Noryum"
VIAddVersionKey /LANG=1034 "FileDescription" "Instalador de Noryum"
VIAddVersionKey /LANG=1034 "FileVersion" "0.1.2"
VIAddVersionKey /LANG=1034 "LegalCopyright" "Noryum"
Section "Noryum"
  SetShellVarContext current
  SetOutPath "$INSTDIR"
  File /r "..\release\Noryum-win32-x64\*"
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  CreateShortcut "$DESKTOP\Noryum.lnk" "$INSTDIR\Noryum.exe"
  CreateShortcut "$SMPROGRAMS\Noryum.lnk" "$INSTDIR\Noryum.exe"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Noryum" "DisplayName" "Noryum"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Noryum" "DisplayVersion" "0.1.2"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Noryum" "UninstallString" '$\"$INSTDIR\Uninstall.exe$\"'
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Noryum" "InstallLocation" "$INSTDIR"
SectionEnd
Section "Uninstall"
  SetShellVarContext current
  Delete "$INSTDIR\chrome_100_percent.pak"
  Delete "$INSTDIR\chrome_200_percent.pak"
  Delete "$INSTDIR\d3dcompiler_47.dll"
  Delete "$INSTDIR\dxcompiler.dll"
  Delete "$INSTDIR\dxil.dll"
  Delete "$INSTDIR\ffmpeg.dll"
  Delete "$INSTDIR\icudtl.dat"
  Delete "$INSTDIR\INICIAR.txt"
  Delete "$INSTDIR\LEEME.md"
  Delete "$INSTDIR\LICENSE"
  Delete "$INSTDIR\LICENSES.chromium.html"
  Delete "$INSTDIR\locales\af.pak"
  Delete "$INSTDIR\locales\am.pak"
  Delete "$INSTDIR\locales\ar.pak"
  Delete "$INSTDIR\locales\bg.pak"
  Delete "$INSTDIR\locales\bn.pak"
  Delete "$INSTDIR\locales\ca.pak"
  Delete "$INSTDIR\locales\cs.pak"
  Delete "$INSTDIR\locales\da.pak"
  Delete "$INSTDIR\locales\de.pak"
  Delete "$INSTDIR\locales\el.pak"
  Delete "$INSTDIR\locales\en-GB.pak"
  Delete "$INSTDIR\locales\en-US.pak"
  Delete "$INSTDIR\locales\es-419.pak"
  Delete "$INSTDIR\locales\es.pak"
  Delete "$INSTDIR\locales\et.pak"
  Delete "$INSTDIR\locales\fa.pak"
  Delete "$INSTDIR\locales\fi.pak"
  Delete "$INSTDIR\locales\fil.pak"
  Delete "$INSTDIR\locales\fr.pak"
  Delete "$INSTDIR\locales\gu.pak"
  Delete "$INSTDIR\locales\he.pak"
  Delete "$INSTDIR\locales\hi.pak"
  Delete "$INSTDIR\locales\hr.pak"
  Delete "$INSTDIR\locales\hu.pak"
  Delete "$INSTDIR\locales\id.pak"
  Delete "$INSTDIR\locales\it.pak"
  Delete "$INSTDIR\locales\ja.pak"
  Delete "$INSTDIR\locales\kn.pak"
  Delete "$INSTDIR\locales\ko.pak"
  Delete "$INSTDIR\locales\lt.pak"
  Delete "$INSTDIR\locales\lv.pak"
  Delete "$INSTDIR\locales\ml.pak"
  Delete "$INSTDIR\locales\mr.pak"
  Delete "$INSTDIR\locales\ms.pak"
  Delete "$INSTDIR\locales\nb.pak"
  Delete "$INSTDIR\locales\nl.pak"
  Delete "$INSTDIR\locales\pl.pak"
  Delete "$INSTDIR\locales\pt-BR.pak"
  Delete "$INSTDIR\locales\pt-PT.pak"
  Delete "$INSTDIR\locales\ro.pak"
  Delete "$INSTDIR\locales\ru.pak"
  Delete "$INSTDIR\locales\sk.pak"
  Delete "$INSTDIR\locales\sl.pak"
  Delete "$INSTDIR\locales\sr.pak"
  Delete "$INSTDIR\locales\sv.pak"
  Delete "$INSTDIR\locales\sw.pak"
  Delete "$INSTDIR\locales\ta.pak"
  Delete "$INSTDIR\locales\te.pak"
  Delete "$INSTDIR\locales\th.pak"
  Delete "$INSTDIR\locales\tr.pak"
  Delete "$INSTDIR\locales\uk.pak"
  Delete "$INSTDIR\locales\ur.pak"
  Delete "$INSTDIR\locales\vi.pak"
  Delete "$INSTDIR\locales\zh-CN.pak"
  Delete "$INSTDIR\locales\zh-TW.pak"
  Delete "$INSTDIR\Noryum.exe"
  Delete "$INSTDIR\resources\app\dist\assets\index-69dTTCoa.css"
  Delete "$INSTDIR\resources\app\dist\assets\index-aM_Tb_MM.js"
  Delete "$INSTDIR\resources\app\dist\assets\index-CfvywHaD.js"
  Delete "$INSTDIR\resources\app\dist\assets\index-Cqkyq58e.css"
  Delete "$INSTDIR\resources\app\dist\assets\index-CXa8SlVM.js"
  Delete "$INSTDIR\resources\app\dist\icon.ico"
  Delete "$INSTDIR\resources\app\dist\icon.png"
  Delete "$INSTDIR\resources\app\dist\index.html"
  Delete "$INSTDIR\resources\app\dist\mark.svg"
  Delete "$INSTDIR\resources\app\dist-desktop\main.cjs"
  Delete "$INSTDIR\resources\app\dist-desktop\main.cjs.map"
  Delete "$INSTDIR\resources\app\dist-desktop\preload.cjs"
  Delete "$INSTDIR\resources\app\dist-desktop\preload.cjs.map"
  Delete "$INSTDIR\resources\app\package.json"
  Delete "$INSTDIR\resources\default_app.asar"
  Delete "$INSTDIR\resources.pak"
  Delete "$INSTDIR\snapshot_blob.bin"
  Delete "$INSTDIR\v8_context_snapshot.bin"
  Delete "$INSTDIR\version"
  Delete "$INSTDIR\vk_swiftshader.dll"
  Delete "$INSTDIR\vk_swiftshader_icd.json"
  Delete "$INSTDIR\vulkan-1.dll"
  RMDir "$INSTDIR\resources\app\dist-desktop"
  RMDir "$INSTDIR\resources\app\dist\assets"
  RMDir "$INSTDIR\resources\app\dist"
  RMDir "$INSTDIR\resources\app"
  RMDir "$INSTDIR\resources"
  RMDir "$INSTDIR\locales"
  Delete "$INSTDIR\Uninstall.exe"
  RMDir "$INSTDIR"
  Delete "$DESKTOP\Noryum.lnk"
  Delete "$SMPROGRAMS\Noryum.lnk"
  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Noryum"
SectionEnd
